### ISSUE TITLE
[prefer-stateless-function] should check if component has ES7 decorator

### ISSUE THREAD

**Issue by dmt0** [jsx-eslint/eslint-plugin-react#501] opened 2016-03-15 19:59 UTC
ES7 decorators only work with classes and not with functions. If a decorator is present [react/prefer-stateless-function] should not be recommended.

**Comment by ljharb** [comment] 2016-03-15 20:27
Decorators are not ES7, and part of the proposal absolutely might be that they work with function declarations. They also certainly work with concise object methods as well.

**Comment by Kerumen** [comment] 2016-03-16 13:52
Related https://github.com/yannickcr/eslint-plugin-react/issues/491#issuecomment-196749779

**Comment by thewillhuang** [comment] 2016-07-23 01:45
@ljharb thats great and all, but the current proposal is with classes, and until that has been agreed upon and or implemented this is still a false positive.

**Comment by ljharb** [comment] 2016-07-23 05:43
@thewillhuang "and properties". https://github.com/wycats/javascript-decorators#object-literal-method-declaration - it is NOT a bug, it is an *essential* part of the proposal.

**Comment by thewillhuang** [comment] 2016-07-26 02:44
ah i see, missed that part completely

**Comment by ljharb** [comment] 2022-02-02 20:05
Decorators remain stage 2, and have changed 3-4 times since this was filed.

However, we do support them via the TS eslint parser.

Additionally, the likely state of the proposal will exclude functions, so we should use the presence of a class decorator as an indication that the component should not be a stateless function.

**Comment by golopot** [comment] 2022-06-04 09:20
fixed in https://github.com/jsx-eslint/eslint-plugin-react/pull/1086

**Closed** 2022-06-04 14:58 UTC
Labels: help wanted, typescript
