### ISSUE TITLE
[Bug]: Not compatible with eslint

### ISSUE THREAD

**Issue by ejgutierrez74** [jsx-eslint/eslint-plugin-react#3775] opened 2024-06-27 10:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

I want to update my current react-app with npm update, im facing an error of compatibility....

```
eduardo@MiPcLinux:~/Descargas/workshop-react$ npm update
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: workshop-react@0.0.0
npm error Found: eslint@9.5.0
npm error node_modules/eslint
npm error   eslint@"^9.3.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.3
npm error node_modules/eslint-plugin-react
npm error   dev eslint-plugin-react@"^7.34.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/eduardo/.npm/_logs/2024-06-27T09_59_34_909Z-eresolve-report.txt

npm error A complete log of this run can be found in: /home/eduardo/.npm/_logs/2024-06-27T09_59_34_909Z-debug-0.log

```

Log file:
```

'Log files:
/home/eduardo/.npm/_logs/2024-06-27T09_59_34_909Z-debug-0.log

# npm resolution error report

While resolving: workshop-react@0.0.0
Found: eslint@9.5.0
node_modules/eslint
  eslint@"^9.3.0" from the root project

Could not resolve dependency:
peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.3
node_modules/eslint-plugin-react
  dev eslint-plugin-react@"^7.34.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```
Link to the project: https://github.com/ejgutierrez74/workshop-react-eduardo

npm update

### Expected Behavior

update eslint and eslint-react-plugin to latest versions....

### eslint-plugin-react version

7.34.1

### eslint version

9.3.0

### node version

20.12.2

**Comment by lorenz-maurer** [comment] 2024-06-27 11:45
I'm in the same boat here. 

```
npm ERR! Found: eslint@9.5.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.3
npm ERR! node_modules/eslint-plugin-react
npm ERR!   dev eslint-plugin-react@"^7.34.3" from the root project
```

**Comment by ljharb** [comment] 2024-06-27 16:31
It's not a bug, we're just not compatible with v9 yet - which means you can't upgrade until we are, or until you stop using this plugin.

Duplicate of #3699.

**Closed by ljharb** 2024-06-27 16:31 UTC
Labels: bug

**Comment by ejgutierrez74** [comment] 2024-06-27 18:46
Sorry i didnt find the duplicate, is there any ETA or version release when eslint-react would be compatible with eslint 9 ? How is the work going ?

**Comment by ljharb** [comment] 2024-06-27 18:55
Follow #3759; there's no ETA or timeline yet.
