### ISSUE TITLE
How to configure with `eslint.config.js` with ESM?

### ISSUE THREAD

**Issue by rakleed** [jsx-eslint/eslint-plugin-react#3685] opened 2024-02-02 13:25 UTC
Can you please add information in the README on how to set up the plugin and config when using flat config in ESLint (`eslint.config.js`) with ESM?

**Comment by ljharb** [comment] 2024-02-02 15:02
PRs are welcome, but i don’t use flat config yet.

**Comment by rdebeasi** [comment] 2024-02-08 18:58
My understanding is that eslint-plugin-react isn't yet compatible with the new flat config format: #3688

**Comment by ljharb** [comment] 2024-02-08 19:00
Indeed, but eslint has FlatCompat for that.

**Comment by rdebeasi** [comment] 2024-02-08 19:08
Ah cool! So could this issue could be resolved with docs explaining how to use FlatCompat with eslint-plugin-react?

**Comment by ljharb** [comment] 2024-02-08 19:14
That would be a fine interim solution, yes - altho we'd just link to eslint's explanation, we don't need any prose here.

**Comment by rdebeasi** [comment] 2024-02-09 21:06
I realized that the [Configuration (new: eslint.config.js)](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#configuration-new-eslintconfigjs) section in the readme covers setup with flat files.

@rakleed are you looking for a version of this documentation that uses ESM instead of CommonJS? Or is this documentation missing some other information that you need?

**Comment by rakleed** [comment] 2024-02-09 21:24
> @rakleed, are you looking for a version of this documentation that uses ESM instead of CommonJS?

Yes, exactly.

**Comment by rdebeasi** [comment] 2024-02-09 21:55
Ah, thanks for clearing that up! An ESM version of that documentation would replace `require` and `module.exports` with `import` and `export default`, like this:

```js
import reactRecommended from 'eslint-plugin-react/configs/recommended';

export default [
  …
  reactRecommended, // This is not a plugin object, but a shareable config object
  …
];
```

A readme a with two versions of each example would be helpful for folks who are using ESM, but it could difficult to read and maintain. Perhaps the readme could include a single ESM example, or a link to more details about the difference between ESM and CommonJS?

**Comment by ljharb** [comment] 2024-02-09 21:57
I think that if translating the basic CJS example to ESM in your head requires documentation, then *using* native ESM is probably a bit premature.

**Comment by rakleed** [comment] 2024-02-13 17:19
@rdebeasi thanks, this works for most cases, although [you need to add the `.js` extension](https://github.com/jsx-eslint/eslint-plugin-react#:~:text=If%20your%20eslint.config.js%20is%20ESM%2C%20include%20the%20.js%20extension%20(e.g.%20eslint%2Dplugin%2Dreact/recommended.js).), which is strange since all other configs with ESLint Flat Config support do not have such a requirement.

But in my case it doesn't work. I'm using the [Airbnb config for React](https://www.npmjs.com/package/eslint-config-airbnb), which [doesn't support Flat Config](https://github.com/airbnb/javascript/issues/2804), so I use the [`FlatCompat` utility](https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config). But when I then add `reactJsxRuntime`, the console displays the error `Error: Key "plugins": Cannot redefine plugin "react".`

Here is my example:
```js
import reactJsxRuntime from 'eslint-plugin-react/configs/jsx-runtime.js';

export default [
  …
  ...compat.extends('airbnb', 'airbnb/hooks'),
  reactJsxRuntime,
  …
];
```

**Comment by rdebeasi** [comment] 2024-02-14 14:36
Oh interesting! That sounds like a different problem from what's described in this issue. If you no longer need the readme update, consider closing this issue.

If you'd like to dig into that issue further, you could:
- Try the same thing with `.eslintrc` to determine whether this issue occurs only when using flat files
- Create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem
- File a new ticket with that example and steps to reproduce

Caveat: I'm not associated with the `eslint-pluign-react` project and I don't know much about this codebase. These are just some general troubleshooting steps that I use! 😄

**Comment by GerroDen** [comment] 2024-07-18 11:57
Am I missing something? I see in docs there are flat configs exported. But I cannot find the flat configs that in the actual code.

**Comment by ljharb** [comment] 2024-07-18 16:31
@GerroDen be sure you're looking at the docs for the last released tag on github - everywhere on github, things on main might be unreleased.

**Comment by magne4000** [comment] 2024-07-22 17:11
The plugin lacks [exports](https://nodejs.org/api/packages.html#exports) definitions in [package.json](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/package.json), which is why we see errors with some Typescript or ESM configs.
Example in [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier/blob/51324d9cdf8b883e2a392904d0f73da9eca6a808/package.json#L18).

**Comment by ljharb** [comment] 2024-07-22 17:23
@magne4000 since adding `exports` is a breaking change, it can't be added within v7. Separately, there shouldn't be any need for exports definitions - without them, everything is accessible. If you mean that native ESM requires specifying file extensions, that's sadly true, and `exports` would indeed be able to omit them.

**Comment by ljharb** [comment] 2024-07-22 17:23
The latest version (v7.35.0) supports eslint 9 and flat config.

Please file a new issue if you're having trouble with that version.

**Closed by ljharb** 2024-07-22 17:23 UTC
