### ISSUE TITLE
[Bug]: TypeError: Error while loading rule 'react/prefer-stateless-function': [[GeneratorState]] is not present on O

### ISSUE THREAD

**Issue by know7no** [jsx-eslint/eslint-plugin-react#3627] opened 2023-08-29 06:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

When I executed ` eslint src --ext js jsx ts tsx ` , the teminal throw out the  'react/prefer-stateless-function' error

ESLint: 8.21.0

TypeError: Error while loading rule 'react/prefer-stateless-function': `[[GeneratorState]]` is not present on `O`

eslint src --ext js jsx ts tsx

### Expected Behavior

I found out that there is  no problem when I use v7.32.1 , hope fix this problem

### eslint-plugin-react version

v7.32.2

### eslint version

8.21.0

### node version

16.14.0

**Comment by ljharb** [comment] 2023-08-29 15:18
Duplicate of #3624. Root cause: https://github.com/es-shims/iterator-helpers/issues/4

**Closed by ljharb** 2023-08-29 15:18 UTC
Labels: bug

**Comment by know7no** [comment] 2023-08-30 03:44
I'm using yarn V1.22.19.

**Comment by ljharb** [comment] 2023-08-30 04:42
In that case, I suspect a yarn resolution bug - ^1.0.5 of es-iterator-helpers is required, but somehow v1.0.3 gets installed. Does that match your node_modules?

**Comment by know7no** [comment] 2023-08-30 06:13
No, I got V1.0.14 installed. It looks ok.

**Comment by ljharb** [comment] 2023-08-30 06:22
oh sorry, i meant internal-slot :-)

**Comment by know7no** [comment] 2023-08-30 09:12
You are absolutely right, thanks a lot.
I did install internal-slot@1.0.3, when I execute `yarn` command. 
After I put  internal-slot@1.0.5 in devDependencies which I think is as same as  in the resolution field ,  the problem  is fixed.

**Comment by mckelveygreg** [comment] 2023-10-17 18:25
Ran into this problem as well, with yarn berry, running `yarn dedupe internal-slot` help clear everything up!

**Comment by know7no** [comment] 2023-10-18 03:12
> Ran into this problem as well, with yarn berry, running `yarn dedupe internal-slot` help clear everything up!

A smart way to fixed this problem. 
When you use yarnV1, you can use `npx yarn-deduplicate yarn.lock` to do this as well.
