### ISSUE TITLE
[Bug]: typescript-eslint v6 deprecation warnings

### ISSUE THREAD

**Issue by thomasmarr** [jsx-eslint/eslint-plugin-react#3689] opened 2024-02-10 19:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Latest recommended preset has a at least one rule that is using deprecated typeParameters property from typescript-eslint. See https://typescript-eslint.io/linting/troubleshooting/#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings

When running tests I see hundreds of instances of "DeprecationWarning: The 'typeParameters' property is deprecated on CallExpression nodes. Use 'typeArguments' instead. See https://typescript-eslint.io/linting/troubleshooting#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings." in console output.

If I remove "plugin:react/recommended" from the extends property of eslintConfig, the warnings are removed.

There's a fix described at the above link which keeps backward compat with v5 and looks pretty straightforward.

### Expected Behavior

Expect no deprecation warnings.

### eslint-plugin-react version

v7.33.2

### eslint version

v8.56.0

### node version

v20.10.0

**Comment by ljharb** [comment] 2024-02-10 21:52
Duplicate of #3602. Will be fixed by #3629.

**Closed by ljharb** 2024-02-10 21:52 UTC
Labels: bug
