### ISSUE TITLE
react/no-unknown-property: invalid property download found on tag <a>

### ISSUE THREAD

**Issue by Enase** [jsx-eslint/eslint-plugin-react#3411] opened 2022-09-05 16:38 UTC
The `react/no-unknown-property` rule reports the`download` property of `<a>` tag as invalid.

**Comment by ljharb** [comment] 2022-09-05 16:44
This was fixed by #3394, and is a duplicate of #3399.

**Closed by ljharb** 2022-09-05 16:44 UTC
