### ISSUE TITLE
[react/jsx-one-expression-per-line] moves text to the beginning of line

### ISSUE THREAD

**Issue by lkazberova** [jsx-eslint/eslint-plugin-react#2318] opened 2019-06-23 16:33 UTC
Hi! I tried to use "react/jsx-one-expression-per-line" rule, but its behaviour is very strange and I don't know how can I fix it.

Sandbox : https://codesandbox.io/s/gatsby-starter-default-f7u3w , please do `npm run lint` in terminal

My config `.eslintrc.json`
```json
{
   "parserOptions": {
        "ecmaVersion": 10,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "plugins": [
        "react"
    ],
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "rules": {
        "react/jsx-one-expression-per-line": [2, { "allow": "none" }]
    }
}
```

Before running `eslint --fix`
```html
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
```
After applying eslint
```html
    <h1>
Hi people
</h1>
    <p>
Welcome to your new Gatsby site.
</p>
    <p>
Now go build something great.
</p>
```

**Comment by ljharb** [comment] 2019-06-23 16:42
By itself it looks weird, but if you also enable the jsx-indent rule it will fix the indentation.

**Comment by lkazberova** [comment] 2019-06-23 17:37
@ljharb  thank you for a quick answer!
I changed my rules  
```json
    "rules": {
        "react/jsx-one-expression-per-line": [2, { "allow": "none" }],
        "react/jsx-indent": [2, 2]
    }
```
but nothing changed with result 😞

**Comment by yannickcr** [comment] 2019-06-23 18:01
The `fix` instruction of `react/jsx-one-expression-per-line` will just add some line breaks between any expression that are on the same line. If you want the tags to be correctly indented aferward then you need to enable `react/jsx-indent`.

However `react/jsx-indent` do not re-indent text nodes (https://github.com/yannickcr/eslint-plugin-react/commit/798f2cab06be270f46843530040ab534512e221a). 

That's why we're getting:

```jsx
    <h1>
Hi people
      <button/>
    </h1>
```
instead of
```jsx
    <h1>
      Hi people
      <button/>
    </h1>
```

Surely there is some room for improvements here.

**Comment by ljharb** [comment] 2019-06-23 18:02
I would expect it to reindent text nodes.

**Comment by lkazberova** [comment] 2019-06-23 18:04
@yannickcr @ljharb  tso it's a good reason for making PR 😃

**Comment by rfgamaral** [comment] 2019-07-01 12:16
Here's one possible workaround until the issue is fixed:

Before running `eslint --fix`

```jsx
<h1><React.Fragment>Hi people</React.Fragment><button/></h1>
```

After applying eslint

```jsx
<h1>
  <React.Fragment>Hi people</React.Fragment>
  <button/>
</h1>
```

You can read more about React Fragments [here](https://reactjs.org/docs/fragments.html) if you don't know about them. But basically, the final rendered DOM tree will be like this:

```html
<h1>
  Hi people
  <button/>
</h1>
```

You don't have to worry about `<React.Fragment>` adding an additional DOM element.

**Comment by rodomeista** [comment] 2019-12-27 18:08
Bumping this thread - are there any intentions to resolve this issue? Having to write react fragments to properly support this feature seems a bit excessive, especially for devs who aren't sure *why* fragments are being used.

**Comment by ljharb** [comment] 2019-12-27 18:22
Yes, it should be fixed somehow. A PR with failing test cases would be a great start.

**Comment by ROSSROSALES** [comment] 2022-06-15 18:03
Hi @ljharb, could I try to tackle this?

**Comment by ljharb** [comment] 2022-06-16 18:10
@ROSSROSALES go for it!

**Comment by ROSSROSALES** [comment] 2022-06-25 17:55
Hi @ljharb, I used @lkazberova code as a testing example.
I recreated the same scenario initially mentioned June 23, 2019, and  I did not come across the same issue.
Below is the proper output of eslint with appropriate rules.

rules:
```
    "rules": {
        "react/jsx-one-expression-per-line": [2, { "allow": "none" }],
        "react/jsx-indent": [2, 2]
    },
```
Sample Code Below:
Before running `npx eslint index.js --fix`
```
  <Layout>
    <SEO title="Home" />
    <h1>{"Hi people"}<button/></h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <h1>Hi people<button/></h1>
    <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
      <Image />
    </div><Link to="/page-2/">Go to page 2</Link>
  </Layout>
```
Errors found from Eslint according to rules `npx eslint index.js`
```
  11:9   error  `{"Hi people"}` must be placed on a new line                     react/jsx-one-expression-per-line
  11:22  error  `button` must be placed on a new line                            react/jsx-one-expression-per-line
  12:8   error  `Welcome to your new Gatsby site.` must be placed on a new line  react/jsx-one-expression-per-line
  13:8   error  `Now go build something great.` must be placed on a new line     react/jsx-one-expression-per-line
  14:9   error  `Hi people` must be placed on a new line                         react/jsx-one-expression-per-line
  14:18  error  `button` must be placed on a new line                            react/jsx-one-expression-per-line
  17:11  error  `Link` must be placed on a new line                              react/jsx-one-expression-per-line
  17:31  error  `Go to page 2` must be placed on a new line                      react/jsx-one-expression-per-line
```
After applying `npx eslint index.js --fix`
```
  <Layout>
    <SEO title="Home" />
    <h1>
      {"Hi people"}
      <button/>
    </h1>
    <p>
      Welcome to your new Gatsby site.
    </p>
    <p>
      Now go build something great.
    </p>
    <h1>
      Hi people
      <button/>
    </h1>
    <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
      <Image />
    </div>
    <Link to="/page-2/">
      Go to page 2
    </Link>
  </Layout>
```
Is there still a need to continue to look into this issue?
If so, please let me know.

**Comment by ljharb** [comment] 2022-06-25 21:02
@ROSSROSALES awesome - in that case, what we need is a PR adding a passing test case, and that PR can close this issue :-)

**Comment by ROSSROSALES** [comment] 2022-06-26 23:43
@ljharb I will work on it! :thumbsup:

**Closed** 2022-07-06 04:22 UTC
Labels: enhancement, help wanted
