### ISSUE TITLE
`jsx-no-leaked-render` performs redundant props check and invalid fix in coerce mode

### ISSUE THREAD

**Issue by wialy** [jsx-eslint/eslint-plugin-react#3431] opened 2022-09-11 11:33 UTC
# Context

There is a sample `Checkbox` component:

```typescript
const Checkbox = ({
  isChecked = false,
  isIndeterminate = false,
}: {
  isChecked?: boolean;
  isIndeterminate?: boolean;
}) => (
  <input 
    checked={isIndeterminate ? false : isChecked} 
    type="checkbox"
  />
);
```

The eslint config file contains a rule:

```
"react/jsx-no-leaked-render": ["error", { validStrategies: ["coerce"] }],
```

# Expected behavior

Linting the code raises no issues

# Actual behavior 

1. Eslint displays an error for the line:

```typescript
checked={isIndeterminate ? false : isChecked}
```

```
Potential leaked value that might cause unintentionally rendered values or rendering crasheseslint[react/jsx-no-leaked-render](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-no-leaked-render.md)
```

2. When auto-fix is performed, the code above is replaced with

```typescript
checked={!!isIndeterminate && false} 
```

which causes the logical issues (the `isChecked` is removed in that case).

**Comment by ljharb** [comment] 2022-09-11 15:07
isChecked could be undefined, according to the types, and default arguments aren’t something that can really be used reliably with static analysis - so i think the warning may be correct.

I agree, though, that the autofix is incorrect - it should be fixing it to `!isIndeterminate && isChecked`

**Comment by ljharb** [comment] 2022-09-11 15:08
cc @Belco90

**Comment by himanshu007-creator** [comment] 2022-11-01 14:52
hey, would like to work on this issue

**Comment by ljharb** [comment] 2022-11-01 15:06
Go for it!

**Comment by himanshu007-creator** [comment] 2022-11-01 15:07
i was not able to reproduce the issue

**Comment by ljharb** [comment] 2022-11-01 15:13
In that case, can you make a PR with passing test cases, and it can close this issue?

**Comment by tcl333** [comment] 2022-11-29 00:16
I had an identical situation to the OP, and this error still occurred. @himanshu007-creator, did you remember to change the allowed strategies to only `coerce`?

**Closed** 2022-12-27 06:19 UTC
Labels: bug, help wanted
