### ISSUE TITLE
[Bug]: Support for Eslint 9.0.0?

### ISSUE THREAD

**Issue by lcsvcn** [jsx-eslint/eslint-plugin-react#3730] opened 2024-04-08 21:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Expected Behavior

Support for the Eslint 9?

<img width="668" alt="Screenshot 2024-04-08 at 18 37 22" src="https://github.com/jsx-eslint/eslint-plugin-react/assets/6011385/d77e3ba0-c05e-465d-857a-07e6432a78b4">

### eslint-plugin-react version

v7.34.1

### eslint version

v9.0.0

### node version

v18.15.0

**Comment by ljharb** [comment] 2024-04-08 21:40
Duplicate of #3699.

**Closed by ljharb** 2024-04-08 21:40 UTC
Labels: bug
