### ISSUE TITLE
[Bug]: `reactPlugin.configs.flat.recommended` part in documentation throws error

### ISSUE THREAD

**Issue by unnamed92** [jsx-eslint/eslint-plugin-react#3790] opened 2024-07-23 20:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Code snippet from documentation throws error as there is no `flat` field in `configs` object

![image](https://github.com/user-attachments/assets/c292cf0b-df25-43c3-a2b8-4029611fa94e)

I'm running `yarn eslint` command

### Expected Behavior

My eslint.config.js:
```
// @ts-check

import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import reactPlugin from "eslint-plugin-react";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...reactPlugin.configs.flat.recommended
);

```

### eslint-plugin-react version

7.35.0

### eslint version

9.7.0

### node version

20.11.0

**Comment by unnamed92** [comment] 2024-07-24 08:42
> I managed to get it working by omitting `flat`, so `reactPlugin.configs.flat.recommended` becomes `reactPlugin.configs.recommended`.

How did you use `reactPlugin.configs.recommended`? I've tried to add it to `tseslint.config` function and spreading it there and both options are returning errors

**Comment by cyrus01337** [comment] 2024-07-24 11:08
> How did you use `reactPlugin.configs.recommended`? I've tried to add it to `tseslint.config` function and spreading it there and both options are returning errors

Here's an example of what I did. It required a bit of messing around through the documentation also and a bit of printing to find out what I was really working with once I came across the same issue as you.

**Comment by unnamed92** [comment] 2024-07-24 14:05
> > How did you use `reactPlugin.configs.recommended`? I've tried to add it to `tseslint.config` function and spreading it there and both options are returning errors
> 
> Here's an example of what I did. It required a bit of messing around through the documentation also and a bit of printing to find out what I was really working with once I came across the same issue as you:
> 
> https://github.com/haotian2006/MyDocs/blob/cyrus01337/fix-eslint/eslint.config.js#L14-L25
> 
> Edit: Would help if I included it :^)

Yes indeed your example doesn't throw errors but please note that in `recommended` object there are a lot of rules that aren't present in `jsx-runtime.js`. So I guess we can't use `jsx-runtime.js` instead of `recommended`

**Comment by ljharb** [comment] 2024-07-24 18:47
I'm a bit confused; `flat` definitely exists in `configs`, and `configs.flat.recommended` exists as well. Are you sure you have v7.35.0 installed?

**Comment by starkfire** [comment] 2024-07-25 23:32
I don't know if this could be of any help since it sounds ridiculous, but what worked on my end is to update my `package.json` to specifically use v7.35.0 before running `pnpm install` once again:

```json
{
  "devDependencies": {
    "eslint-plugin-react": "^7.35.0"
  }
}
```

Before this change, I've had v7.34.3.

```json
{
  "devDependencies": {
    "eslint-plugin-react": "^7.34.3"
  }
}
```

In my case, it seems like the package manager does not always guarantee that the plugin will be updated to v7.35.0, even if you have a caret on your version tag. This worked for ESLint v8 and v9.

**Comment by ljharb** [comment] 2024-07-26 04:05
I believe it is pnpm's default behavior to prefer the oldest, instead of the latest, version. To know what you have installed, you always need to check the package.json on disk for the package in node_modules (or your lockfile), not your local package.json

Closing on that assumption; @unnamed92 if you're not using pnpm and can confirm you have v7.35.0 *on disk* I'll reopen.

**Closed by ljharb** 2024-07-26 04:05 UTC
Labels: bug

**Comment by dd-jonas** [comment] 2024-08-02 12:34
@ljharb I can confirm that `.flat` does not exist according to TypeScript. I have v7.35.0 installed (I can confirm that this version is in my node_modules).

![Screenshot 2024-08-02 at 14 33 58](https://github.com/user-attachments/assets/e33e4f04-d011-4cff-ac3c-be27bca86d38)

**Comment by skyclouds2001** [comment] 2024-08-07 07:17
> @ljharb I can confirm that `.flat` does not exist according to TypeScript. I have v7.35.0 installed (I can see this in my node_modules).
> 
> ![Screenshot 2024-08-02 at 14 33 58](https://private-user-images.githubusercontent.com/69415794/354595117-e33e4f04-d011-4cff-ac3c-be27bca86d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQ5MjAsIm5iZiI6MTcyMzAxNDYyMCwicGF0aCI6Ii82OTQxNTc5NC8zNTQ1OTUxMTctZTMzZTRmMDQtZDAxMS00Y2ZmLWFjM2MtYmUyN2JjYTg2ZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWZiOTM3NjkyNzYyNmY0Y2UyZDllMjEyZWNkNTQ0MGRhMjU4NGRiZDcwZTY4YjFlNmQyZTIyNGNhYTQ2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pOkJ6PzUpN696AckR8wmZxm4FvE46c148NceR_rtJQ0)

![image](https://github.com/user-attachments/assets/e2c5e5d9-9030-4121-95d5-d76b0ea39300)

flat config existed according to the source code, but does not existed in the IDE suggestion

**Comment by ljharb** [comment] 2024-08-07 09:15
We don't ship TS types, so if there's a bug with the DT types for this plugin, then that's where it needs to be filed.

What shows up in autocomplete or the types is irrelevant; only runtime matters.

**Comment by skyclouds2001** [comment] 2024-08-07 14:20
> I could not find a types package for eslint-plugin-react so I'm not sure where the types are coming from. I also don't see this documented in the setup guide.

this is autoo detected by the IDE
